# Generated by Django 6.1 on 2026-08-30 18:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدائرة')),
                ('branch_name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(max_length=15, verbose_name='الرقم الوطني / الهوية')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف المحمول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('ticket_type', models.CharField(choices=[('INQUIRY', 'استفسار عام عن خدمة'), ('COMPLAINT', 'شكوى'), ('SUGGESTION', 'اقتراح'), ('TECH_ISSUE', 'مشكلة تقنية')], max_length=50, verbose_name='نوع الطلب / الاستفسار')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الموضوع')),
                ('details', models.TextField(verbose_name='تفاصيل الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('ai_classification', models.CharField(blank=True, max_length=100, null=True, verbose_name='تصنيف الذكاء الاصطناعي')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('citizen', 'مواطن'), ('employee', 'موظف'), ('admin', 'مدير/مسؤول')], default='citizen', max_length=20, verbose_name='الصلاحية')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bawbaty_app.department', verbose_name='جهة العمل (للموظفين)')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان الشكوى')),
                ('description', models.TextField(verbose_name='تفاصيل الشكوى')),
                ('ai_classification', models.CharField(blank=True, max_length=100, null=True, verbose_name='تصنيف الذكاء الاصطناعي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='رقم التتبع')),
                ('status', models.CharField(choices=[('submitted', 'تقديم الطلب'), ('auditing', 'التدقيق الإداري'), ('matching', 'المطابقة والاستلام'), ('closed', 'إغلاق المعاملة'), ('rejected', 'مرفوض')], default='submitted', max_length=20, verbose_name='حالة الطلب')),
                ('payment_status', models.BooleanField(default=False, verbose_name='حالة الدفع')),
                ('receipt_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الإيصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المواطن')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=50, verbose_name='الحالة الجديدة')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة الموظف/المسؤول')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bawbaty_app.request', verbose_name='المعاملة')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخدمة')),
                ('fees', models.CharField(default='مجانية', max_length=100, verbose_name='الرسوم')),
                ('execution_time', models.CharField(default='فوري', max_length=100, verbose_name='مدة التنفيذ')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bawbaty_app.department', verbose_name='الدائرة الحكومية')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bawbaty_app.service', verbose_name='الخدمة'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الموعد')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المواطن')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bawbaty_app.department', verbose_name='الدائرة الحكومية')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bawbaty_app.service', verbose_name='الخدمة المطلوبة')),
            ],
        ),
    ]
