# Generated by Django 6.1 on 2026-09-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bawbaty_app', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ai_classification',
        ),
    ]
